version: '3.3'
services:
  
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    network_mode: host
  
  clickhouse:
      image: clickhouse/clickhouse-server
      ports:
      - "8123:8123"
      - "9000:9000"
      environment:
        CLICKHOUSE_DB: 'hezzl'
        CLICKHOUSE_USER: 'user'
        CLICKHOUSE_PASSWORD: 'password'
      volumes:
      - ch-data:/var/lib/clickhouse
      network_mode: host
  
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data
    environment:
        REDIS_PASSWORD: 'hezzl'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    network_mode: host
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    environment:
      PG_URL: 'postgres://user:pass@localhost:5432/postgres'
      REDIS_PASSWORD: 'hezzl'
      CLICKHOUSE_PASSWORD: 'password'
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - clickhouse
      - redis
    network_mode: host
volumes:
    pg-data:
    ch-data: 
    cache:
    

