app:
  name: 'hezzl_task5'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
  pg_url: 'postgres://user:pass@localhost:5432/postgres' ## move to env

clickhouse:
  ch_host: 'localhost'
  ch_port: '8123'
  db_name: 'hezzl'
  username: 'default' ## move to env
  password: 'default' ## move to env
