app:
  name: 'iamthe1whoknocks/hezzl_test_task'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

clickhouse:
  ch_host: 'localhost'
  ch_port: '9000'
  db_name: 'hezzl'
  username: 'user' 
  engine: ''

redis:
  redis_host: 'localhost'
  redis_port: '6379'
  redis_db: 0
  redis_ttl: 60

nats:
  host: 'localhost'
  port: '4222'
  topic: 'topic'
  batch_count: 5 ## batch to send to clickhouse
